// algo-info.js
// Definitions, working principles, complexity, and SLAM/ADAS use cases
// for the INFO tab — content mirrors the desktop visualizer.py ALGO_INFO
// dictionary so the web and desktop versions stay consistent.

const ALGO_INFO = {
  bfs: {
    name: "BFS",
    fullName: "Breadth-First Search",
    category: "Uninformed Search",
    color: "#38bdf8",
    definition:
      "BFS explores a graph level by level — all neighbours at distance 1 from start, then distance 2, and so on. It uses a QUEUE (FIFO) as its core data structure, ensuring the shallowest node is always processed first.",
    principle: [
      "Enqueue start node, mark it visited.",
      "Dequeue the front node.",
      "If it is the GOAL — stop and trace back the path.",
      "Enqueue all unvisited neighbours, mark them visited.",
      "Repeat from step 2 until the queue is empty.",
    ],
    complexity: [
      ["Time", "O(V + E)", "V = vertices, E = edges"],
      ["Space", "O(V)", "Entire frontier stored in queue"],
    ],
    optimal: true, optimalNote: "Shortest path (fewest hops) on unweighted graphs",
    complete: true, completeNote: "Always finds a path if one exists",
    pros: ["Guarantees shortest path (unweighted)", "Simple and easy to implement", "Complete — never misses a solution"],
    cons: ["High memory: entire frontier kept in queue", "No concept of edge cost or weights", "Slower than A* on large weighted maps"],
    slam: "Frontier-based exploration — BFS finds the nearest unexplored frontier cell from the robot's current position, guiding autonomous map-building.",
    adas: "Flood-fill occupancy-grid traversal. Free-space reachability checks before route planning.",
    tip: "Watch the BLUE cells expand outward in concentric rings — each ring is one BFS level. Every cell in a ring is the same number of steps from Start.",
  },
  dfs: {
    name: "DFS",
    fullName: "Depth-First Search",
    category: "Uninformed Search",
    color: "#a78bfa",
    definition:
      "DFS dives as deep as possible along one branch before backtracking to try another. It uses a STACK (LIFO). Because it commits to one direction first, the path it finds is NOT guaranteed to be shortest.",
    principle: [
      "Push start node onto stack.",
      "Pop the top node. If GOAL — stop and trace path.",
      "If already visited — skip.",
      "Mark current node visited.",
      "Push all unvisited neighbours onto stack.",
      "Repeat from step 2.",
    ],
    complexity: [
      ["Time", "O(V + E)", "Same asymptotic as BFS"],
      ["Space", "O(depth)", "Only current path kept in memory"],
    ],
    optimal: false, optimalNote: "Path found is not guaranteed to be shortest",
    complete: true, completeNote: "In finite graphs without repeated states",
    pros: ["Very low memory (only stores current branch)", "Fast when goal is deep along one branch", "Foundation of maze generation algorithms"],
    cons: ["Does NOT find shortest path", "Can waste time in wrong long branches", "Poor choice for optimal path planning"],
    slam: "Connectivity checks — verifying the map graph stays connected after adding an obstacle. Also used in topological map analysis.",
    adas: "Rarely used directly in ADAS path planning. Appears in dependency-graph analysis of driving scenarios.",
    tip: "Notice the path plunges deep in one direction first, then backtracks — very different from BFS rings. The final path is often longer than BFS.",
  },
  dijkstra: {
    name: "Dijkstra",
    fullName: "Dijkstra's Shortest Path Algorithm",
    category: "Cost-based (Informed) Search",
    color: "#fbbf24",
    definition:
      "Dijkstra finds the shortest path in a WEIGHTED graph by maintaining a priority queue ordered by cumulative cost g(n) from start. It guarantees the optimal path for any non-negative edge weights, making it the backbone of GPS navigation worldwide.",
    principle: [
      "Set dist[start] = 0, dist[all others] = infinity.",
      "Push (0, start) onto a min-heap priority queue.",
      "Pop node with LOWEST cost — this is now 'settled'.",
      "For each neighbour: new_cost = current_cost + edge_cost.",
      "If new_cost < dist[neighbour] → update and push to heap.",
      "Repeat until goal is settled.",
    ],
    complexity: [
      ["Time", "O((V+E) log V)", "With binary min-heap"],
      ["Space", "O(V)", "Distance table + heap"],
    ],
    optimal: true, optimalNote: "For any non-negative edge weights",
    complete: true, completeNote: "",
    pros: ["Optimal for any non-negative cost graph", "Works on weighted road networks", "Foundation of all GPS route planning"],
    cons: ["Explores in all directions — no goal awareness", "Slower than A* on grid maps (no heuristic)", "On uniform grids: behaves identically to BFS"],
    slam: "ROS costmap planning — grid cells have cost based on obstacle proximity (inflation radius). Dijkstra finds minimum-cost path through inflated costmap.",
    adas: "Road network routing (city to city or intersection to intersection). Core of HERE Maps, Google Maps, TomTom routing engines.",
    tip: "On this uniform-cost grid Dijkstra looks just like BFS — both expand as circles. The real difference appears on weighted maps where roads have different costs.",
  },
  astar_m: {
    name: "A* Manhattan",
    fullName: "A* with Manhattan Distance Heuristic",
    category: "Heuristic (Informed) Search",
    color: "#22c55e",
    definition:
      "A* extends Dijkstra by adding a HEURISTIC h(n) — an estimate of remaining cost to the goal. It always expands the node with lowest f(n) = g(n) + h(n). Manhattan distance h = |dr| + |dc| is admissible (never overestimates) for 4-directional grid movement, guaranteeing an optimal path while exploring far fewer nodes.",
    principle: [
      "f(n) = g(n) + h(n)",
      "g(n) = actual cost from start to n",
      "h(n) = |row_n − row_goal| + |col_n − col_goal|",
      "Pop node with LOWEST f. If GOAL — done.",
      "For each neighbour: compute new g and f, update if cheaper.",
      "Heuristic MUST be admissible for optimality.",
    ],
    complexity: [
      ["Time", "O(E log V)", "With good heuristic: far less than Dijkstra"],
      ["Space", "O(V)", "Open set + closed set"],
      ["h(n)", "Admissible", "Manhattan never overestimates 4-dir cost"],
    ],
    optimal: true, optimalNote: "Manhattan heuristic is admissible for 4-dir movement",
    complete: true, completeNote: "",
    pros: ["Much faster than Dijkstra in practice", "Heuristic guides search directly toward goal", "Industry standard for grid-based robot planning"],
    cons: ["4-directional movement only (no diagonals)", "Manhattan h is inadmissible with diagonal moves"],
    slam: "ROS navigation stack global_planner (navfn package) — A* on the costmap. The most common global planner used in real robot deployments.",
    adas: "Lane-level path planning on HD maps. Grid-based parking lot and campus navigation systems.",
    tip: "The BLUE frontier forms a DIAMOND shape pointing toward the goal — the heuristic pulls the search in the right direction. Compare how many fewer cells it visits vs Dijkstra.",
  },
  astar_e: {
    name: "A* Euclidean",
    fullName: "A* with Euclidean Distance + 8-Directional Movement",
    category: "Heuristic (Informed) Search",
    color: "#14b8a6",
    definition:
      "Same algorithm as A* Manhattan, but uses h = √(dr² + dc²) and allows 8-directional movement including diagonals. Diagonal moves cost √2 ≈ 1.414. This produces shorter, more natural paths that better approximate real robot motion.",
    principle: [
      "f(n) = g(n) + h(n)",
      "h(n) = √((r−goal_r)² + (c−goal_c)²)",
      "8 directions: straight cost = 1.0, diagonal cost = 1.414",
      "Euclidean h is admissible for 8-dir movement.",
      "Same expand loop as A* Manhattan.",
    ],
    complexity: [
      ["Time", "O(E log V)", "Fewer nodes explored than Manhattan"],
      ["Space", "O(V)", "Open set + closed set"],
      ["h(n)", "Admissible", "For 8-dir with diagonal cost √2"],
    ],
    optimal: true, optimalNote: "Euclidean heuristic admissible for 8-dir movement",
    complete: true, completeNote: "",
    pros: ["Shorter, more natural diagonal paths", "Explores even fewer cells than Manhattan A*", "Better path quality for real robot motion"],
    cons: ["Slightly more computation per step (sqrt)", "Inadmissible if diagonal moves are disallowed"],
    slam: "Smooth path generation on costmaps for robots that can rotate freely. Better path quality for differential-drive and holonomic robots.",
    adas: "Continuous-like grid trajectory planning. Autonomous parking systems where diagonal manoeuvres are natural.",
    tip: "The path takes DIAGONAL shortcuts — compare its length to A* Manhattan on the same maze. The frontier shape is more circular (Euclidean vs diamond).",
  },
  apf: {
    name: "Potential Field",
    fullName: "Artificial Potential Field (APF)",
    category: "Reactive / Force-based Planning",
    color: "#ec4899",
    definition:
      "APF models the robot as a particle moving in an artificial force field. The GOAL generates an attractive potential that pulls the robot toward it. Every OBSTACLE generates a repulsive potential that pushes the robot away. At each step the robot moves in the direction of the combined net force — no explicit path is searched.",
    principle: [
      "Attractive force: F_att = k_att × (goal − position)",
      "Repulsive force per obstacle (within radius d0):",
      "F_rep = k_rep × (1/d − 1/d0) × (1/d²) × direction",
      "Net force = F_att + sum(all F_rep)",
      "Normalise force, move one step in that direction.",
      "If stuck (|F| ≈ 0): add a random kick to escape.",
    ],
    complexity: [
      ["Per step", "O(obstacles)", "Force from each obstacle computed"],
      ["Overall", "< 1 ms/step", "Real-time capable at 100+ Hz"],
    ],
    optimal: false, optimalNote: "Reactive method, not globally optimal",
    complete: false, completeNote: "Can get stuck in local minima (valleys in potential)",
    pros: ["Extremely fast: real-time at 100+ Hz", "Smooth, natural-looking curved trajectories", "No grid needed — works in continuous space", "Naturally handles dynamic moving obstacles"],
    cons: ["LOCAL MINIMA: robot can get trapped in potential valleys", "Oscillations in narrow corridors", "No completeness or optimality guarantee", "k_att and k_rep need careful tuning"],
    slam: "Local planner in ROS move_base — runs at sensor rate (10-50 Hz) to handle dynamic obstacles while A* handles global routing on the static costmap.",
    adas: "Real-time pedestrian and vehicle avoidance. Runs at 20-100 Hz on live LiDAR/camera detections. Used in Tesla Autopilot, Mobileye, Bosch ADAS systems.",
    tip: "The path curves around obstacles organically — not a discrete grid search, but a continuous force flow. May jitter near dense walls (local minima); smoothest on open grids.",
  },
  dstar: {
    name: "D* Lite",
    fullName: "D* Lite — Dynamic A* (Lite version)",
    category: "Dynamic Replanning Algorithm",
    color: "#f97316",
    definition:
      "D* Lite solves the same problem as A* but is designed for environments that CHANGE during navigation. It plans backward from goal to start, then INCREMENTALLY REPAIRS the plan when obstacles are discovered — updating only affected nodes rather than replanning from scratch. Originally developed for Mars rovers.",
    principle: [
      "Search backward: from GOAL toward START.",
      "Maintain g(s) = current cost, rhs(s) = one-step lookahead.",
      "Node is 'inconsistent' when g(s) ≠ rhs(s).",
      "Robot moves along the plan step by step.",
      "When map changes: mark affected nodes inconsistent.",
      "Re-propagate ONLY the changed region — plan is repaired, not rebuilt.",
    ],
    complexity: [
      ["Initial plan", "O((V+E) log V)", "Same as A*"],
      ["Per replan", "O(k log V)", "k = affected nodes (often tiny)"],
    ],
    optimal: true, optimalNote: "Always optimal given the current known map",
    complete: true, completeNote: "",
    pros: ["Far faster replanning than full A* replan", "Scales to large maps with local changes", "Used on NASA Mars rovers (Spirit, Opportunity)"],
    cons: ["More complex to implement than A*", "Overhead of maintaining rhs values", "Overkill if the map never changes"],
    slam: "SLAM live navigation — as LiDAR scans reveal new walls or remove old ones, D* Lite repairs the current plan locally. Standard in ROS navigation with dynamic maps.",
    adas: "When a pedestrian steps into the lane or a car brakes suddenly — D* Lite instantly repairs the planned trajectory without a full recompute.",
    tip: "WATCH THE DEMO: the path is shown first, then a new wall appears mid-path. D* Lite clears and repairs the plan — only the affected portion gets re-explored. That's the whole point of the algorithm.",
  },
};
